import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from "../providers/WalletProvider";
import { UserContextProvider } from "@/providers/UserContextProvider";
import { ContractContextProvider } from "@/providers/ContractContextProvider";

export const metadata: Metadata = {
  title: "Lease Agreement dApp",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <WalletProvider>
          <ContractContextProvider>
            <UserContextProvider>{children}</UserContextProvider>
          </ContractContextProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
